name: CD Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Minikube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Minikube
        uses: manusa/actions-setup-minikube@v2
        with:
          minikube-version: 'latest'
          kubernetes-version: 'v1.24.0'

      - name: Start Minikube
        run: minikube start --driver=none

      - name: Deploy Backend
        run: |
          kubectl apply -f kubernetes/postgres-pvc.yaml
          kubectl apply -f kubernetes/postgres-deployment.yaml
          kubectl apply -f kubernetes/backend-deployment.yaml

      - name: Deploy Frontend
        run: |
          kubectl apply -f kubernetes/frontend-deployment.yaml
          kubectl apply -f kubernetes/ingress.yaml